name: Update Dependencies

on:
  schedule:
    - cron: '0 0 * * 0' # 每周日午夜运行

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install
        run: pnpm install

      - name: Update
        run: npx npm-check-updates -u && pnpm install

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update dependencies
          title: Update dependencies
          body: This PR updates dependencies to their latest versions
          branch: 'update-dependencies/${{ github.head_ref }}'
